export interface Fichatecnicabienes
    {
        FicId : number;
        TibId : number;
        IntBId : number;
        ResNroConcepto : object;
        SosId : number;
        DocId : number;
        FicTitulo : object;
        FicAutor : object;
        FicFechaElaboracionObra : object;
        FicTecnica : object;
        FicDimensiones : object;
        FicPropietario : object;
        FicNroDocumentoIdentidad : object;
        FicObservaciones : string;
        FicFoto : object;
        TobId : number;
        FicConsecutivoObra : string;
        FicConsecutivoSeguridad : object;
        CltId : number;
        Cantidad : object;
        FicAlto : object;
        FicLargo : object;
        FicAncho : object;
        FicProfundidad : object;
        FicEspesor : object;
        TepId : number;
        IdFirmado : object;
        CtlPadreId : number;
        TitId : number;
        CtlHijoId : number;
        BasTiposDocumentosIdentidad : object;
        PatSipaConceptoObras : object[];
        PatSolicitudSalidaObras : object;
        PatAnexos : object[];
    }
